#! /bin/sh

sxhkd &

if [ -x $HOME/.scripts/laptop_dual_monitor ]; then
    $HOME/.scripts/laptop_dual_monitor
    bspc monitor DP1 -d 1 2 3 4 5
    bspc monitor eDP1 -d 6 7 8 9 0
else
    bspc monitor -d I II III IV V VI VII VIII IX X
fi

bspc config border_width         0
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config border_radius        15

bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Godot_Engine state=floating

$HOME/.config/polybar/launch.sh
picom &
dunst &
nm-applet 2>&1 &
blueman-applet &
wal -i /usr/share/backgrounds/

if ! pgrep -U $USER xautolock >/dev/null; then
    $HOME/.scripts/xautolock-script
fi

if ! pgrep -U $USER redshift-gtk >/dev/null; then
    redshift-gtk -l 39.17:-85.51
fi
