#!/bin/bash

alias config='user/bin/git --git-dir=$HOME/.cfg/ --work-tree=$HOME'
echo ".cfg" >> .gitignore
git clone --bare git@github.com:evogelsa/dotfiles.git $HOME/.cfg
mkdir -p .config.bak && \
    config checkout 2>&1 | egrep "\s+\." | awk {'print $1'} | \
    xargs -I{} mv {} .config.bak/{}
config checkout
config config --local status.showUntrackedFiles no

