#!/bin/bash

external_monitor=$(xrandr --query | grep -e '\<DP1\>')
if [[ $external_monitor = *connected* ]]; then
    xrandr --output eDP1 --mode 1920x1080 --rotate normal --output DP1 --primary --mode 2560x1440 --rotate normal --right-of eDP1
fi
